.TH i-spy-notify 1

.SH NAME
i-spy-notify - execute scripts for each Freedesktop notification

.SH SYNOPSIS

.B i-spy-notify
[
.B --help
] [
.B --config
.I FILE
] [
.B --mode
.I MODE
]

.SH DESCRIPTION

I Spy Notify lets you watch Linux desktop notifications and run scripts for each notification. It's great for logging, displaying popups, and playing sounds.

The configuration file is
.B ~/.config/i-spy-notify/i-spy-notify.json
.
